" Overall settings
set nu
set rnu
set wildmenu
set hidden
set incsearch
set scrolloff=3 " Keep 3 lines below and above the cursor

" Key mappings
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
