" Plugins
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive' " Git integration within Vim
Plug 'morhetz/gruvbox' " Colorscheme of choice
Plug 'tpope/vim-surround' " Management of 'surrounding pairs'
Plug 'tpope/vim-commentary' " Easy commenting/uncommenting
Plug 'vim-airline/vim-airline' " Status bar with relevant info on bottom of screen
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " Simple FZF Wrapper for Vim
Plug 'junegunn/fzf.vim' " More advanced FZF functions
Plug 'dense-analysis/ale' " Code linting for many languages

call plug#end()

" Overall settings
set nu
set rnu
set wildmenu
set hidden
set incsearch
set hlsearch
set scrolloff=3 " Keep 3 lines below and above the cursor
set background=dark " Gruvbox dark version
let g:gruvbox_italic=1
" TODO: Figure out why contrast settings don't seem to make a difference
colorscheme gruvbox
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#poetv#enabled = 1
let g:ale_linters = {'python': ['flake8', 'pylint']}
let g:ale_fixers = {'python': ['yapf']}
let g:ale_fix_on_save = 1

" Identation
set expandtab
set autoindent
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4

" Key mappings
let mapleader = " "
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
nnoremap <leader>gst :Git<CR>
nnoremap <leader>gci :Gcommit<CR>
nnoremap <leader>gpush :Gpush<CR>
nnoremap <leader>gpull :Gpull<CR>
nnoremap <leader>gf :Gfetch<CR>
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <C-h> :bprevious<CR>
nnoremap <C-j> :Buffers<CR>
nnoremap <C-k>  :bdelete<CR>
nnoremap <C-l> :bnext<CR>
nnoremap <leader>of :Files<CR>
nnoremap <leader>ff :Rg<CR>
nnoremap <leader>fix :ALEFix<CR>
cmap w!! w !sudo tee > /dev/null %
