" Overall settings
set nu
set rnu
set wildmenu
set hidden
set incsearch
set scrolloff=3 " Keep 3 lines below and above the cursor

" Identation
set expandtab
set autoindent
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4

" Key mappings
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Plugins

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive' " Git integration within Vim

call plug#end()
